# Generated by Django 4.0.3 on 2022-04-07 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Forsqrt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_number', models.FloatField(blank=True, null=True)),
                ('second_number', models.FloatField(blank=True, null=True)),
                ('third_number', models.FloatField(blank=True, null=True)),
                ('res_1', models.FloatField(blank=True, null=True)),
                ('res_2', models.FloatField(blank=True, null=True)),
                ('unsolvable', models.CharField(max_length=50)),
            ],
        ),
    ]
